# Generated by Django 5.2.7 on 2026-01-17 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('external_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('external_id', models.IntegerField(unique=True)),
                ('normal_price', models.FloatField(default=0)),
                ('sale_price', models.FloatField(default=0)),
                ('currency', models.CharField()),
                ('discount_percent', models.IntegerField(default=0)),
                ('url', models.CharField()),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='deals.store')),
            ],
        ),
    ]
