# Generated by Django 5.2.7 on 2026-02-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0003_subscriber_subscription_notificationlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationlog",
            name="is_sent",
            field=models.BooleanField(default=False),
        ),
    ]
